// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fakedata.actions;

import java.util.Date;
import java.util.Random;
import com.github.javafaker.Faker;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GenerateDateBetween extends CustomJavaAction<java.util.Date>
{
	private java.util.Date BeginDate;
	private java.util.Date EndDate;

	public GenerateDateBetween(IContext context, java.util.Date BeginDate, java.util.Date EndDate)
	{
		super(context);
		this.BeginDate = BeginDate;
		this.EndDate = EndDate;
	}

	@java.lang.Override
	public java.util.Date executeAction() throws Exception
	{
		// BEGIN USER CODE
		Random random = new Random();
		Faker faker = new Faker(random);
		Date dateBetween = faker.date().between(this.BeginDate, this.EndDate);
		return dateBetween;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateDateBetween";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
