// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fakedata.actions;

import java.util.Random;
import com.github.javafaker.Faker;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import fakedata.proxies.FakeDataStringType;

/**
 * Generate a fake string, choosing from a range of possibilities. All this data comes from Faker
 */
public class GenerateFakeString extends CustomJavaAction<java.lang.String>
{
	private fakedata.proxies.FakeDataStringType Parameter;

	public GenerateFakeString(IContext context, java.lang.String Parameter)
	{
		super(context);
		this.Parameter = Parameter == null ? null : fakedata.proxies.FakeDataStringType.valueOf(Parameter);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Random random = new Random(this.getContext().getRequestStartTime());
		Faker faker = new Faker(random);
		
		if (this.Parameter == null) {
			return "";
		}

		if (this.Parameter.equals(FakeDataStringType.CompanyName)) {
			return faker.company().name().toString();
		} else if (this.Parameter.equals(FakeDataStringType.Chuck_Norris_Fact)) {
			return faker.chuckNorris().fact().toString();
		} else if (this.Parameter.equals(FakeDataStringType.AppName)) {
			return faker.app().name().toString();
		} else if (this.Parameter.equals(FakeDataStringType.HashMD5)) {
			return faker.crypto().md5().toString();
		} else if (this.Parameter.equals(FakeDataStringType.HashSHA1)) {
			return faker.crypto().sha1().toString();
		} else if (this.Parameter.equals(FakeDataStringType.HashSHA256)) {
			return faker.crypto().sha256().toString();
		} else if (this.Parameter.equals(FakeDataStringType.HashSHA512)) {
			return faker.crypto().sha512().toString();
		}
		
		return "";
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateFakeString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
