// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fakedata.actions;

import java.util.Random;
import com.github.javafaker.Faker;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GenerateNumberBetween extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Long Min;
	private java.lang.Long Max;

	public GenerateNumberBetween(IContext context, java.lang.Long Min, java.lang.Long Max)
	{
		super(context);
		this.Min = Min;
		this.Max = Max;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		Random random = new Random(this.getContext().getRequestStartTime());
		Faker faker = new Faker(random);
		
		Long min = (this.Min > this.Max) ? this.Max : this.Min;
		Long max = (this.Max < this.Min) ? this.Min : this.Max;
		
		return faker.number().numberBetween(min, max);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateNumberBetween";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
