// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fakedata.actions;

import com.github.javafaker.Faker;
import com.github.javafaker.service.FakeValuesService;
import com.github.javafaker.service.RandomService;
import com.mendix.systemwideinterfaces.core.IContext;
import java.util.Locale;
import java.util.Random;
import com.mendix.webui.CustomJavaAction;

/**
 * Use the Faker random service to create your own random string using an expression. Example:
 * 
 * #{Name.first_name}
 * 
 * Please read the documentation: http://dius.github.io/java-faker/apidocs/index.html
 * 
 * 
 * 
 */
public class GenerateRandomStringFromFaker extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Locale;
	private java.lang.String Expression;

	public GenerateRandomStringFromFaker(IContext context, java.lang.String Locale, java.lang.String Expression)
	{
		super(context);
		this.Locale = Locale;
		this.Expression = Expression;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Locale locale = this.Locale != "" ? new Locale(this.Locale) : new Locale("en-US");
		if (this.Expression == "") {
			return "";
		}
		
		Random random = new Random(this.getContext().getRequestStartTime());
		Faker faker = new Faker(random);
		FakeValuesService service = new FakeValuesService(locale, new RandomService(random));
		
		try {
			return service.expression(this.Expression, faker);
		} catch (Exception e) {
			// TODO: handle exception
			return "Unknown/wrong expression :: " + this.Expression;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateRandomStringFromFaker";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
