// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fakedata.actions;

import java.util.Locale;
import com.github.javafaker.service.FakeValuesService;
import com.github.javafaker.service.RandomService;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Generates a random string using a mask. The following characters will be replaced:
 * 
 * # - random number
 * ? - random letter
 * 
 * So if you try to generate an ID that starts with 2 letters, a dash, and 4 numbers, your mask should be:
 * 
 * '??-####'
 * 
 * 
 */
public class GenerateRandomString extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Mask;
	private java.lang.Boolean Uppercase;

	public GenerateRandomString(IContext context, java.lang.String Mask, java.lang.Boolean Uppercase)
	{
		super(context);
		this.Mask = Mask;
		this.Uppercase = Uppercase;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.Mask == "") {
			return "";
		}
		
		FakeValuesService service = new FakeValuesService(new Locale("en-GB"), new RandomService());
		return service.bothify(this.Mask, this.Uppercase);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateRandomString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
