// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fakedata.actions;

import java.util.Random;
import com.github.javafaker.Faker;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import fakedata.proxies.QuoteType;

public class GenerateQuote extends CustomJavaAction<java.lang.String>
{
	private fakedata.proxies.QuoteType Parameter;

	public GenerateQuote(IContext context, java.lang.String Parameter)
	{
		super(context);
		this.Parameter = Parameter == null ? null : fakedata.proxies.QuoteType.valueOf(Parameter);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Random random = new Random(this.getContext().getRequestStartTime());
		Faker faker = new Faker(random);
		
		if (this.Parameter == null) {
			return "";
		} else if (this.Parameter.equals(QuoteType.Back_to_the_future)) {
			return faker.backToTheFuture().quote();
		} else if (this.Parameter.equals(QuoteType.Chuck_Norris)) {
			return faker.chuckNorris().fact();
		} else if (this.Parameter.equals(QuoteType.Friends)) {
			return faker.friends().quote();
		} else if (this.Parameter.equals(QuoteType.Game_of_Thrones)) {
			return faker.gameOfThrones().quote();
		} else if (this.Parameter.equals(QuoteType.Harry_Potter)) {
			return faker.harryPotter().quote();
		} else if (this.Parameter.equals(QuoteType.Hitchhikers_Guide_To_The_Galaxy)) {
			return faker.hitchhikersGuideToTheGalaxy().quote();
		} else if (this.Parameter.equals(QuoteType.Hobbit)) {
			return faker.hobbit().quote();
		} else if (this.Parameter.equals(QuoteType.How_I_Met_Your_Mother)) {
			return faker.howIMetYourMother().quote();
		} else if (this.Parameter.equals(QuoteType.Rick_And_Morty)) {
			return faker.rickAndMorty().quote();
		} else if (this.Parameter.equals(QuoteType.Yoda)) {
			return faker.yoda().quote();
		}
		
		return "";
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateQuote";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
