// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fakedata.actions;

import java.util.Locale;
import com.github.javafaker.service.FakeValuesService;
import com.github.javafaker.service.RandomService;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Use a regex for generating a string: https://github.com/mifmif/Generex
 */
public class GenerateRandomRegexString extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Regex;

	public GenerateRandomRegexString(IContext context, java.lang.String Regex)
	{
		super(context);
		this.Regex = Regex;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.Regex == "") {
			return "";
		}
		
		FakeValuesService service = new FakeValuesService(new Locale("en-GB"), new RandomService());		
		return service.regexify(this.Regex);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateRandomRegexString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
